config/routes.rb
Blocipedia::Application.routes.draw do

  resources :wikis do
    resources :collaborators
  end

  devise_for :users

  get '/users/enter_payment', to: 'users#enter_payment'

  resources :users do
    member do
      post 'pay'
    end
  end

  resources :charges

  get "welcome/index"

  get "welcome/about"

  root to: 'welcome#index'
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user

    # if a member, they can manage their own posts 
    # (or create new ones)
    if user.role? :member
      can :manage, Wiki, :user_id => user.id
    end

    # Moderators can delete any post
    if user.role? :moderator
      can :read, Wiki
      can :manage, Wiki :collaborators => { :user_id => user.id }
    end

    # Admins can do anything
    if user.role? :admin
      can :manage, :all
    end
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  attr_accessible :wiki_id, :user_id

  belongs_to :user
  belongs_to :wiki

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  attr_accessible :amount, :stripe_txn_id, :user_id

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :username, 
  :ispremium, :payments

  has_many :wikis, through: :collaborators
  has_many :collaborators, dependent: :destroy
  has_many :payments

  def ispremium
  end
  
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  attr_accessible :body, :title

  has_many :users, through: :collaborators
  has_many :collaborators, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

def new
end

def create
  Stripe.api_key = "sk_test_DVnOiPCwhyZB6FM6UnRGpxgZ"
  token = params[:stripeToken]

  # Create the charge on Stripe's servers - this will charge the user's card
  begin
    charge = Stripe::Charge.create(
      :amount => 500, # amount in cents, again
      :currency => "usd",
      :card => token,
      :description => "payinguser@example.com"
    )
    current_user.update_attribute :is_premium, true
  rescue Stripe::CardError => e
    redirect_to :back
  end
end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  def index
    @colloborator = Collaborator.find(params[:id])
    @users = User.all
    @wiki = Wiki.find(params[:wiki_id])  
  end

  def create
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = @wiki.collaborators.build(params[:collaborator])
    
    if @collaborator.save
      flash[:notice] = "Successfully created collaborator."
    else
      flash[:notice] = "There was an error."
    end

    redirect_to @wiki
  end

  def show
    @colloborator = Collaborator.find(params[:id])
  end

  def new
    @users = User.all
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.new
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])
    @wiki = Wiki.find(params[:wiki_id])

    if @collaborator.destroy
      flash[:notice] = "Collaborator was successfully removed."
      redirect_to @wiki
    else
      flash[:notice] = "Collaborator could not be removed."
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def create
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
  class WikisController < ApplicationController
  def index
    @wikis = Wiki.all
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new(params[:wiki])
    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end
  
  def edit
    @wiki = Wiki.find(params[:id])
    @collaborators = @wiki.collaborators
  end

  def update
    @wiki = Wiki.find(params[:id])
    if @wiki.update_attributes(params[:wiki])
      flash[:notice] = "Post was updated."
      redirect_to @wiki
    else
      flash[:error] = "There was an error saving your wiki. Please try again."
      render :new
    end
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
def markdown(content)
  @markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, space_after_headers: true, fenced_code_blocks: true)
  @markdown.render(content)
end

def include_javascript (file)
    s = " <script type=\"text/javascript\">" + render(:file => file) + "</script>"
    content_for(:head, raw(s))
end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wiki_helper.rb
module WikiHelper
end

app/views/charges/create.html.erb
<h2> Thanks, you paid <strong> $5.00 </strong>! </h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js"
          class="stripe-button"
          data-key="pk_test_vvfQsXC8fAtenN6bGjjVExjy"
          data-description="A month's subscription"
          data-amount="500">
  </script>
<% end %>

app/views/collaborators/index.html.erb
index.html.erb

app/views/collaborators/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <h3>Add Collaborators to Your Wiki </h3>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
  </head>
  <ul>
    <% @users.each do |u| %>
      <%= form_for [@wiki, @collaborator] do |f| %>
        <li>
          <%= u.name %> <%= u.email %>
          <%= f.hidden_field :user_id, :value => u.id %>
          <%= f.submit "Add as collaborator" %>
        </li>
      <% end %>
     
      <% if @wiki.collaborators.pluck("user_id").include? u.id %>
        <% c = Collaborator.where(:user_id => u.id, :wiki_id => @wiki.id).last %>
        <%= button_to 'Delete', wiki_collaborator_path(@wiki, c), :method => 'delete', :confirm => 'Are you sure?' %>
      <% end %>
    <% end %>
  </ul>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="notice"><%= alert %></p>
    <ul>
        <li><%= link_to "Home", welcome_index_path %></li>
    </ul>
 <div class="pull-right user-info">
      <% if current_user %>
        Hello! <%= current_user.email %>! <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path %> or 
        <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
</div>
    
    <%= yield %>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/users/_premium.html.erb
_premium.html.erb

app/views/users/enter_payment.html.erb
<H1> Pay for Premium Blocipedia Services-EP </H1>

<div class="container">
<%= link_to "users#pay", class: 'button', method: :pay do %>
<% end %>
</div>

app/views/users/index.html.erb
<H1> Pay for Premium Blocipedia Services-I </H1>

<div class= "container">
<%= link_to "users#pay", class: 'button', method: :pay do %>
<% end %>
</div>

app/views/users/show.html.erb
<H1> Pay for Premium Blocipedia Services-S </H1>

<div class= "container">
<%= link_to "users#pay", class: 'button', method: :pay do %>
<% end %>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
  <h1><center>Blocipedia</center></h1>
  <h2><center>Create and Share Wikis with Blocipedia</center></h2>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'button' %> or 
      <%= link_to "Sign Up", new_user_registration_path, class: 'button' %> for your Wiki today!
  </p>



<div class="container">
  <div class="sixteen columns">
  </div>
      <div class="eight columns">
        <ul class="square">
          <h1> Free Plan </h1>
          <p> Create Unlimited Wikis </h2>
          </ul>
      </div>
      <div class="eight columns">
         <ul class="square">
          <h1>Premium Plan</h1>
          <p>Create Unlimited and Private Wikis</p>
        </ul>
      </div>
  </div>

app/views/wikis/edit.html.erb
<head>
</head>
<body>
<h1><center>Edit and Preview Your Wiki Entry Real-Time</center></h1>
<div class="container">
  <div class="sixteen columns">
  </div>
  <div class="eight columns">
<%= form_for @wiki, html: { class: 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title %>
    </div>
  </div>
<div class="control-group">
   <h3> Edit Your Wiki Entry </h3>
    <%= f.label :body, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :body, size: "60x20"%>
    </div>
  </div>
<div class="control-group">
  <div class="controls">
    <%= f.submit "Save", class: 'btn' %>
  </div>
</div>
</div>

<div class="eight columns">
<h3> Preview Wiki Entry</h3>
<div id="editor" style="width: 300px; height: 250px; border: 1px solid #ccc; text-size: 12pt">
</div>
</div>
</div>

<h3>Current Wiki Collaborators </h3>
<ul>
  <% @collaborators.each do |c| %>
    <li><%= c.user.id %></li>
  <% end %>
</ul>

<%= link_to 'Add or Delete Collaborators', new_wiki_collaborator_path(@wiki) %>

<% end %>
</body>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<% @wikis.each do |wiki| %>
  <p><%= link_to wiki.title, wiki %></p>
<% end %>

app/views/wikis/new.html.erb
<%= form_for @wiki do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit "Save" %>

<% end %>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<%= link_to "Edit", edit_wiki_path(@wiki), class: 'button' %>

<p><%= markdown(@wiki.body) %></p>